### PR TITLE
FAR, Kerbalism and RealPlume patches

### PR DESCRIPTION
**Pull request by pand5461**
Added FAR compatibility (deleted ModuleParachute if FAR is detected to avoid duplicating ModuleRealChute if RealChute is installed).
Added Kerbalism compatibility (surface and volume auto-detects for pods were just crazy).
Added RealPlume plume to Soyuz SM.

### CODE REVIEW

**Comment by Kerbas-ad-astra** [comment]
Several of your patches use FOR when they should use NEEDS.  (That would trick other mods into thinking that Kerbalism or RealPlumes or whatever is installed.)

**Comment by pand5461** [comment]
Fixed (I hope).

**Comment by Kerbas-ad-astra** [comment]
Sorry to add more comments, but I hesitate to accept a patch to support a complex mod like Kerbalism.  I see that Kerbalism itself hosts patches to support various mods; is there a reason you're not putting the HGR patch over there?

**Comment by pand5461** [comment]
Well, I included too many things without explaining anything about them. Have to move the full patch to the experimental branch, actually.
Now there are only inner surface areas and volumes for pods.
The reason for not putting this to Kerbalism is because I don't think the dev is going to check whether my numbers are sane.
FYI: the "autodetected" surfaces and volumes for all HGR capsules are way over the top (like 7 m3 volume, 15 m2 surface), resulting in insane EC consumption which drains batteries in mere minutes when in shadow.
The other things (that I deleted now) are my thoughts of how life support system could be organized for different Soyuz configurations.

**Comment by Kerbas-ad-astra** [comment]
I don't use Kerbalism at all, so I have no idea whether your numbers are sane, either.  Why submit even the autodetected numbers here and not there?

Furthermore, RealPlume already has HGR patches, so you should submit your patch there (sorry I was late to realize this, they just updated).

Finally, the RealChute patch in this mod already removes the ModuleParachute, so the RealChute/FAR patch you've included is redundant as well.  (Although I will update the "timing" of the patch to run earlier, if that will help.)

**Pull request closed without merging**
